#
# drivers/char/hndprof/Makefile
#
# Makefile for the Linux HND performance profiling char device drivers.
#

include $(TOPDIR)/../../tools/profile/sbprof/target/driver/driver.mk

O_TARGET = bmips3300_perfcnt.o

obj-$(CONFIG_HND_BMIPS3300_PROF) = $(OBJS)

include $(TOPDIR)/Rules.make
